server:
  port: 10002
  netty:
    enable-tcp-package-log: true
    max-connections: 10000
logging:
  level:
    com.github.netty: debug
    org:
      apache:
        tomcat: debug
        coyote: debug